trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    tar --exclude='azure-pipelines.yml' --exclude='.DS_Store' --exclude='.git' --exclude='.gitignore' -czf $(Build.ArtifactStagingDirectory)/TA-index-time.spl .
  displayName: 'Package App'
