trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: custom
    arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
  displayName: 'Install GitVersion'

- script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch
  displayName: 'Determine Version'

- script: tar --exclude='azure-pipelines.yml' --exclude='.git' --exclude='.gitignore' --exclude='GitVersion.yml' -czf $(Build.ArtifactStagingDirectory)/TA-index-time-$(GitVersion.NuGetVersion).spl .
  displayName: 'Package App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/TA-index-time-$(GitVersion.NuGetVersion).spl
    artifactName: 'TA-index-time'

- task: GithubRelease@0 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: triddell
    repositoryName: triddell/TA-index-time
    tagSource: manual
    tag: $(GitVersion.NuGetVersion)      
    assets: $(Build.ArtifactStagingDirectory)/*.spl
