trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    tar --exclude='azure-pipelines.yml' --exclude='.git' --exclude='.gitignore' -czf $(Build.ArtifactStagingDirectory)/TA-index-time.spl .
  displayName: 'Package App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/TA-index-time.spl
    artifactName: 'TA-index-time'